### PR TITLE
remove extra semi colon to fix webpack 5 build issue

### PR DESCRIPTION
**Pull request by peacekeeper**
Same issue as discussed in https://github.com/Semantic-Org/Semantic-UI-CSS/issues/75 and partially fixed in https://github.com/Semantic-Org/Semantic-UI-CSS/pull/76

### CODE REVIEW

**Comment by lubber-de** [comment]
Thanks for the PR. 
The issue has already been solved in the nightly beta of the main repo here
https://github.com/fomantic/Fomantic-UI/pull/2028

However this CSS repo gets automatically updated on new releasses from the main repo only.

**Comment by anthonysgro** [comment]
Hey, this is still not fixed and I have to still manually remove the semi-colon. Can someone review this?

**Comment by lubber-de** [comment]
@anthonysgro See [my comment above](https://github.com/fomantic/Fomantic-UI-CSS/pull/12#issuecomment-1007283549).

**Review by cynner — APPROVED** [review]

**Comment by ryanhugh** [comment]
Looks like the PR for the main repo has been merged. When can we expect this issue to be fixed in this repo?

**Comment by lubber-de** [comment]
> Looks like the PR for the main repo has been merged. When can we expect this issue to be fixed in this repo?

https://twitter.com/fomanticui/status/1570109120208044032

fui290announcement

**Comment by lubber-de** [comment]
Fixed in latest 2.9.0 release

**Pull request closed without merging**
